optim: adadelta
init: xavier_uniform
max_epoch: 250
batch_type: folded
batch_size: 32
optim_conf:
    lr: 0.2
    rho: 0.95
    eps: 1.0e-08
    weight_decay: 0.1
patience: 8
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 1

scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.5
    patience: 1
encoder: rnn
encoder_conf:
    rnn_type: lstm
    bidirectional: true
    use_projection: true
    num_layers: 4
    hidden_size: 320
    output_size: 320
    dropout: 0.0
decoder: rnn
decoder_conf:
    rnn_type: lstm
    num_layers: 1
    hidden_size: 320
    dropout: 0.4
    att_conf:
        atype: location
        adim: 320
model_conf:
    ctc_weight: 0.1
