optim: adadelta
init: xavier_uniform
max_epoch: 30
batch_type: folded
batch_size: 1
optim_conf:
    lr: 1.0
    rho: 0.95
    eps: 1.0e-08
    weight_decay: 0
patience: 4
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 1

scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.5
    patience: 1
input_size: 2048
encoder: wav2vec2
# w2v_url: https://dl.fbaipublicfiles.com/fairseq/wav2vec/xlsr_53_56k.pt
# w2v_url: https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec2_vox_960h_new.pt
# w2v_url: https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_vox_new.pt

encoder_conf:
    output_size: 256
    normalize_before: true
#    freeze_w2v: false
    freeze_finetune_updates: 1000
    w2v_url: https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec2_vox_960h_new.pt
    w2v_dir_path: ./downloads/wav2vec_pretrained_models
#    finetune_last_n_layers: 0


decoder: rnn
decoder_conf:
    rnn_type: lstm
    num_layers: 1
    hidden_size: 320
    dropout: 0.0
    att_conf:
        atype: location
        adim: 320
model_conf:
    ctc_weight: 1.0
