#!/usr/bin/env bash
# THIS FILE IS GENERATED BY tools/setup_anaconda.sh
if [ -z "${PS1:-}" ]; then
    PS1=__dummy__
fi
. /home/marcoyang/asr_project/espnet2/tools/venv/etc/profile.d/conda.sh && conda deactivate && conda activate espnet2
